# This playbook uses the ping module to test connectivity to Linux hosts
- name: Ping
  hosts: localhost

  tasks: 
  - name: ping 
    ping: 
  - name: echo 
    shell: echo Hello World! > hello_world